# Generated by Django 2.2.14 on 2022-12-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221125_1731'),
        ('core', '0008_item_stock'),
    ]

    operations = [
    ]
