# Generated by Django 2.2.14 on 2022-12-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221204_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='anonymous',
        ),
    ]
