# Generated by Django 2.2.14 on 2022-12-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221202_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='ref_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
