# Generated by Django 2.2.14 on 2022-12-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20221202_1134'),
        ('core', '0011_remove_orderitem_anonymous'),
        ('core', '0013_delete_orderupdate'),
    ]

    operations = [
    ]
