# Generated by Django 2.2.14 on 2022-12-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20221209_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
